development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:47c98ec4254777fb36874c888f2c0501@viperfish.redistogo.com:11986/
  password: 47c98ec4254777fb36874c888f2c0501
  host: viperfish.redistogo.com
  port: 11986
  password: 47c98ec4254777fb36874c888f2c0501
  inline: true
  timeout: 1
