# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d86cdb6575fba2b100cefb7b84ade7ef7becac79a2733a51adbcd707b748bc0b5b17cc45a0369e3426d9ab17a74ddd899de45b8e50257f612e01716268ffc7e2

test:
  secret_key_base: 373903468510b4974c13e0dd9c7ef5335507cc099d6054b4e8991a291c05731ac98865c0c59296fc15b5327208afbab73b85ae10239322a71571dc45753d44b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>